# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'ordering': ('is_published', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='BookPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'')),
                ('status', models.IntegerField(choices=[(1, 'Wait'), (2, 'Listen')], default=1, verbose_name='Status')),
                ('order', models.IntegerField()),
                ('last_position', models.IntegerField(default=0, verbose_name='Position')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='player.Book')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
